services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: telegashop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  bot:
    build: .
    env_file: [ .env ]
    depends_on: [ postgres, redis ]
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  pgdata:
